FROM mikinglang/baseline:v8-debian12.6-linux-amd64

# Download the latest version of the miking repository
ENV MIKING_GIT_REMOTE="https://github.com/miking-lang/miking.git"
ENV MIKING_GIT_COMMIT="24505bd"
RUN mkdir -p /src \
 && cd /src \
 && git clone ${MIKING_GIT_REMOTE} \
 && cd /src/miking \
 && git checkout ${MIKING_GIT_COMMIT} \
 && echo "MIKING_GIT_REMOTE=\"$MIKING_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "MIKING_GIT_COMMIT=\"$MIKING_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/miking

# Apply patches if needed
# ADD patches/ /src/patches/
# Historic patch for javascript test case
# RUN patch -u test/js/make.sh < /src/patches/0001-*.patch

RUN eval $(opam env)   \
 && make install       \
 # && make test-all      \
 # && make test-sundials \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="stdlib=/root/.local/lib/mcore/stdlib"

CMD ["mi"]

# Download the latest version of the miking repository
ARG MIKING_DPPL_GIT_REMOTE="https://github.com/treeppl/miking-dppl.git"
ARG MIKING_DPPL_GIT_COMMIT="70fabcc"
RUN mkdir -p /src \
 && cd /src \
 && git clone ${MIKING_DPPL_GIT_REMOTE} \
 && cd /src/miking-dppl \
 && git checkout ${MIKING_DPPL_GIT_COMMIT} \
 && echo "MIKING_DPPL_GIT_REMOTE=\"$MIKING_DPPL_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "MIKING_DPPL_GIT_COMMIT=\"$MIKING_DPPL_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/miking-dppl

RUN eval $(opam env) \
 && make install \
 # && make test \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="coreppl=/root/.local/src/coreppl:$MCORE_LIBS"

CMD ["cppl"]

# Download the latest version of the miking repository
ARG TREEPPL_GIT_REMOTE="https://github.com/treeppl/treeppl.git"
ARG TREEPPL_GIT_COMMIT="a2259e3"
RUN mkdir -p /src \
 && cd /src \
 && git clone ${TREEPPL_GIT_REMOTE} \
 && cd /src/treeppl \
 && git checkout ${TREEPPL_GIT_COMMIT} \
 && echo "MIKING_DPPL_GIT_REMOTE=\"$MIKING_DPPL_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "MIKING_DPPL_GIT_COMMIT=\"$MIKING_DPPL_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/treeppl

RUN eval $(opam env) \
 && make install \
 # && make test \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="treeppl=/root/.local/src/treeppl:$MCORE_LIBS"

CMD ["tpplc"]
