FROM r-base:4.4.2

RUN R -e "install.packages(c('ape', 'tidyverse', 'jsonlite', 'remotes'), repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('maribraga/evolnets')"
RUN R -e "remotes::install_github('treeppl/treepplr', ref = 'bd4e27e')"
